### ISSUE TITLE
`sample` method missing on arrays

### ISSUE THREAD

**Issue by ashes999** [xxuejie/webruby#16]
Hi,

I just discovered this project (which is quite awesome, by the way) and decided to play around with it. One thing that puzzled me is that the `sample` method doesn't work, i.e. `[1, 2, 3].sample`. Is this something that's missing from `mruby` itself? I did some digging, but couldn't find anything about this in the mruby repo, either.

**Comment by xxuejie** [comment]
Thanks for the interest!

I believe `mruby` does support `Array#sample`, the implementation is at [here](https://github.com/mruby/mruby/blob/master/mrbgems/mruby-random/src/random.c#L264). I just tried with my IRB demo at [here](http://qiezi.me/projects/mruby-web-irb/mruby.html#), `sample` did work.

So, I guess this is more of an environment problem, how did you try out webruby? Any chance you can share more information on this(like the version you are using, and the environment you are using)?

**Comment by ashes999** [comment]
Yes, I noticed that too after opening my issue. Certainly, I can share my method.

I couldn't figure out how to build webruby (didn't try). Instead, I swiped the compiled version used from the `webruby irb` link.

- First, I browsed to the ["webruby irb link](http://joshnuss.github.io/mruby-web-irb/) (NB: `sample` doesn't work here, either).
- I clicked `View Source` and downloaded their `webruby.js`
- I created a new `index.html` page referencing that, and called webruby with a hard-coded line:

```
var mrb = WEBRUBY();
mrb.run_script('puts "Sample is #{[1, 2, 3].sample}"');
mrb.close();
```

There's probably something different about their `webruby.js` that makes this happen. I guess I'm better off building my own binaries, since the webruby repo doesn't have release binaries either.

**Comment by xxuejie** [comment]
The webruby irb link you posted was actually created by @joshnuss some time ago, and I think lags a little on the latest advancements here.

Webruby now depends on [emsdk](http://kripken.github.io/emscripten-site/docs/getting_started/downloads.html), which is a big dependency. So it's a little tricky to setup. Basically, you can setup in these steps:

1. Install emsdk following instructions at [here](http://kripken.github.io/emscripten-site/docs/getting_started/downloads.html), and remember to install the latest incoming version
2. Activate the incoming version via instructions on the same page.
3. Follow my old blog post at [here](http://blog.qiezi.me/posts/84793-webruby-is-now-a-gem) on installing webruby, but skip the part relating to LLVM.

I gotta warn you first: the installation steps here require compiling the whole LLVM project, which, depends on your machine, might take either a few minutes to hours of time. The full installation on my mac requires ~6 GB disk space. This is now a huge disadvantage of webruby -_-

Anyway, do let me know if you have any questions!

**Comment by ashes999** [comment]
So you also theorize that the sample I used (pun not intended) was an older version of webruby?

Since you're already releasing versions of this on Ruby Gems, could I also bother you to add releases to this repo, and provide the same, pre-built versions of `webruby.js` (which you're already building) for the rest of us to consume?

Adding 3MB to a web application is, IMO, almost a killer. (If it's a game, it could be worthwhile, because compared to graphics and sounds, it'll be fairly small as a percentage.)

**Comment by xxuejie** [comment]
Yep, I think that's using an older version of webruby.

I can try building a `webruby.js`, but since that repo is maintained by @joshnuss, we will have wait for him to update it.

@joshnuss: any chance you can share the gems you require when building `webruby.js` for your IRB example? I can help build it in case you don't want to go through all the efforts of building LLVM for latest webruby :)

Actually, it's not as bad as 3MB, as of my latest [test](https://twitter.com/defmacro/status/560314625594384384), `webruby.js` is around 1.6MB with optimizations, which is 296kb gzipped. Compared to assets in games(images, sounds), I think this is not an insane overhead.

But I agree, it is still bigger than writing in pure JS :)

**Comment by ashes999** [comment]
Oh, that's confusing. I thought you're providing the webruby.js binaries which he's consuming.  I'll ask over there, thanks.

**Comment by ashes999** [comment]
Actually, maybe you guys can coordinate and figure out who builds it and where to find it. That's all someone really needs to build a webruby-based web app; it takes a couple of lines of code.

We can open a new issue in whatever repository to track that effort.

**Comment by xxuejie** [comment]
[This one](http://qiezi.me/projects/mruby-web-irb/mruby.html) is maintained by me, simple, up-to-date but so ugly.

[This one](http://joshnuss.github.io/mruby-web-irb/) is maintained by @joshnuss, nice, feature-completed, but sometimes lags a little bit :)
